import mongoose from 'mongoose';
import Product from './src/models/Product.js';
import dotenv from 'dotenv';

dotenv.config();

const seedProducts = [
  // STATIONERY (20 products)
  {
    name: 'Cahier A4 Spirale 200 Pages',
    price: 8.5,
    category: 'stationery',
    description: 'Cahier spiralé premium avec feuilles blanches de qualité',
    tags: ['notebook', 'organization', 'exam', 'gre'],
    inStock: true,
  },
  {
    name: 'Stylo Gel BIC Cristal (Lot 10)',
    price: 6.9,
    category: 'stationery',
    description: 'Pack de 10 stylos gel confortables et fiables',
    tags: ['pen', 'exam', 'writing'],
    inStock: true,
  },
  {
    name: 'Surligneurs Couleur Assortis (5 Couleurs)',
    price: 4.5,
    category: 'stationery',
    description: 'Set de 5 surligneurs pour mettre en évidence les passages importants',
    tags: ['highlighter', 'study', 'organization'],
    inStock: true,
  },
  {
    name: 'Post-It Notes 100 Feuilles',
    price: 2.8,
    category: 'stationery',
    description: 'Notes adhésives pour organiser vos tâches',
    tags: ['organization', 'planning', 'productivity'],
    inStock: true,
  },
  {
    name: 'Classeur A4 3 Anneaux',
    price: 9.5,
    category: 'stationery',
    description: 'Classeur robuste pour organiser vos documents',
    tags: ['organization', 'filing', 'study'],
    inStock: true,
  },
  {
    name: 'Feuilles Blanches A4 (Rame 500)',
    price: 7.2,
    category: 'stationery',
    description: 'Rame de 500 feuilles de papier blanc standard',
    tags: ['paper', 'writing', 'printing'],
    inStock: true,
  },
  {
    name: 'Pochette Plastique Transparente (Lot 100)',
    price: 5.5,
    category: 'stationery',
    description: 'Lot de 100 pochettes pour protéger vos documents',
    tags: ['organization', 'storage', 'protection'],
    inStock: true,
  },
  {
    name: 'Correcteur Tipp-Ex 20ml',
    price: 2.2,
    category: 'stationery',
    description: 'Correcteur liquide pour erreurs d\'écriture',
    tags: ['correction', 'writing'],
    inStock: true,
  },
  {
    name: 'Crayons Assortis Maped (12 Couleurs)',
    price: 3.8,
    category: 'stationery',
    description: 'Set de 12 crayons de couleur pour dessins et diagrammes',
    tags: ['coloring', 'creativity', 'visual'],
    inStock: true,
  },
  {
    name: 'Agrafeuse Métallique + Agrafe (5000)',
    price: 11.2,
    category: 'stationery',
    description: 'Agrafeuse robuste avec 5000 agrafes',
    tags: ['office', 'organization', 'binding'],
    inStock: true,
  },
  {
    name: 'Perforatrice 2 Trous',
    price: 8.9,
    category: 'stationery',
    description: 'Perforatrice pour reliure en classeur',
    tags: ['office', 'organization'],
    inStock: true,
  },
  {
    name: 'Scotch Transparent 48mm x 50m',
    price: 1.9,
    category: 'stationery',
    description: 'Rouleau de scotch transparent de haute qualité',
    tags: ['adhesive', 'packing', 'office'],
    inStock: true,
  },
  {
    name: 'Étui Trousse Compartimenté',
    price: 12.5,
    category: 'stationery',
    description: 'Trousse avec compartiments pour ranger stylos et crayons',
    tags: ['storage', 'organization', 'portable'],
    inStock: true,
  },
  {
    name: 'Marque-pages Brillants (Lot 50)',
    price: 3.2,
    category: 'stationery',
    description: 'Lot de 50 marque-pages colorés',
    tags: ['reading', 'organization', 'study'],
    inStock: true,
  },
  {
    name: 'Règle Plastique 30cm',
    price: 1.5,
    category: 'stationery',
    description: 'Règle transparente pour tracer et mesurer',
    tags: ['measurement', 'drawing', 'office'],
    inStock: true,
  },
  {
    name: 'Gomme Staedtler Premium',
    price: 1.8,
    category: 'stationery',
    description: 'Gomme de qualité pour effacer sans laisser de traces',
    tags: ['correction', 'precision'],
    inStock: true,
  },
  {
    name: 'Enveloppes Blanches A5 (Lot 50)',
    price: 4.3,
    category: 'stationery',
    description: 'Lot de 50 enveloppes blanches standards',
    tags: ['mailing', 'office', 'storage'],
    inStock: true,
  },
  {
    name: 'Étiquettes Adhésives Blanches',
    price: 5.6,
    category: 'stationery',
    description: 'Feuille d\'étiquettes adhésives pour étiquetage',
    tags: ['labeling', 'organization'],
    inStock: true,
  },
  {
    name: 'Porte-Bloc A4 en Carton',
    price: 4.7,
    category: 'stationery',
    description: 'Porte-bloc pour prendre des notes rapidement',
    tags: ['organization', 'note-taking', 'portable'],
    inStock: true,
  },
  {
    name: 'Ruban Décorateur Coloré (5 rouleaux)',
    price: 6.8,
    category: 'stationery',
    description: 'Set de 5 rubans décorateurs pour personaliser',
    tags: ['decoration', 'organization'],
    inStock: true,
  },

  // ELECTRONICS (15 products)
  {
    name: 'Calculatrice Scientifique Casio FX-92',
    price: 28.5,
    category: 'electronics',
    description: 'Calculatrice scientifique pour mathématiques et sciences',
    tags: ['calculator', 'math', 'science', 'exam'],
    inStock: true,
  },
  {
    name: 'Clavier Mécanique Compact RGB',
    price: 85.0,
    category: 'electronics',
    description: 'Clavier sans fil avec rétroéclairage pour programmer et étudier',
    tags: ['keyboard', 'peripheral', 'coding', 'gaming'],
    inStock: true,
  },
  {
    name: 'Souris Logitech M705',
    price: 45.0,
    category: 'electronics',
    description: 'Souris sans fil silencieuse pour travail prolongé',
    tags: ['mouse', 'peripheral', 'wireless'],
    inStock: true,
  },
  {
    name: 'Lampe LED Bureau Ajustable',
    price: 38.9,
    category: 'electronics',
    description: 'Lampe LED pour étudier sans fatigue oculaire',
    tags: ['lighting', 'focus', 'study', 'health'],
    inStock: true,
  },
  {
    name: 'Casque Audio Anker Soundcore Life Q30',
    price: 95.5,
    category: 'electronics',
    description: 'Casque noise-cancelling pour concentration',
    tags: ['headphones', 'audio', 'focus', 'music'],
    inStock: true,
  },
  {
    name: 'Hub USB-C 7 en 1',
    price: 48.0,
    category: 'electronics',
    description: 'Hub pour connecter plusieurs périphériques',
    tags: ['connectivity', 'peripheral', 'laptop'],
    inStock: true,
  },
  {
    name: 'Clé USB Sandisk 64GB',
    price: 18.5,
    category: 'electronics',
    description: 'Clé USB haute vitesse pour transporter vos fichiers',
    tags: ['storage', 'backup', 'portable'],
    inStock: true,
  },
  {
    name: 'Disque Dur Externe 1TB',
    price: 68.0,
    category: 'electronics',
    description: 'Disque dur externe pour sauvegarder vos travaux',
    tags: ['storage', 'backup', 'security'],
    inStock: true,
  },
  {
    name: 'Batterie Externe 20000mAh',
    price: 32.5,
    category: 'electronics',
    description: 'Batterie de secours pour téléphone et tablette',
    tags: ['power', 'portable', 'mobile'],
    inStock: true,
  },
  {
    name: 'Adaptateur Courant HDMI 2M',
    price: 12.0,
    category: 'electronics',
    description: 'Câble HDMI pour connecter à écran externe',
    tags: ['connectivity', 'display', 'peripheral'],
    inStock: true,
  },
  {
    name: 'Webcam HD 1080p',
    price: 42.0,
    category: 'electronics',
    description: 'Webcam pour visioconférences et enregistrements',
    tags: ['video', 'online-learning', 'communication'],
    inStock: true,
  },
  {
    name: 'Microphone Condensateur USB',
    price: 55.0,
    category: 'electronics',
    description: 'Microphone pour enregistrement audio de qualité',
    tags: ['audio', 'recording', 'presentation'],
    inStock: true,
  },
  {
    name: 'Chargeur Rapide 65W USB-C',
    price: 38.5,
    category: 'electronics',
    description: 'Chargeur rapide pour laptop et téléphone',
    tags: ['charging', 'fast-charging', 'portable'],
    inStock: true,
  },
  {
    name: 'Montre Connectée Smartwatch',
    price: 89.0,
    category: 'electronics',
    description: 'Montre intelligente pour gérer temps et notifications',
    tags: ['time-management', 'wearable', 'productivity'],
    inStock: true,
  },
  {
    name: 'Crayon Numérique pour Tablette',
    price: 62.5,
    category: 'electronics',
    description: 'Stylet pour prendre des notes sur tablette',
    tags: ['writing', 'digital', 'tablet', 'note-taking'],
    inStock: true,
  },

  // BOOKS (15 products)
  {
    name: 'Dictionnaire Français-Arabe Larousse',
    price: 22.5,
    category: 'books',
    description: 'Dictionnaire complet pour traductions',
    tags: ['reference', 'language', 'study'],
    inStock: true,
  },
  {
    name: 'Livre Mathematics: Calculus',
    price: 68.0,
    category: 'books',
    description: 'Manuel complet de calcul pour L2/L3',
    tags: ['math', 'calculus', 'engineering'],
    inStock: true,
  },
  {
    name: 'Programmation Python: Guide Complet',
    price: 52.0,
    category: 'books',
    description: 'Guide pratique de Python pour débutants',
    tags: ['programming', 'python', 'coding'],
    inStock: true,
  },
  {
    name: 'Histoire de la Science Moderne',
    price: 45.5,
    category: 'books',
    description: 'Exploration des développements scientifiques',
    tags: ['history', 'science', 'culture'],
    inStock: true,
  },
  {
    name: 'Guide Business: Entrepreneuriat 101',
    price: 38.0,
    category: 'books',
    description: 'Introduction à l\'entrepreneuriat et gestion',
    tags: ['business', 'entrepreneurship', 'management'],
    inStock: true,
  },
  {
    name: 'Medical Anatomy Textbook - Arabic',
    price: 95.0,
    category: 'books',
    description: 'Livre d\'anatomie médicale en arabe',
    tags: ['medicine', 'anatomy', 'health'],
    inStock: true,
  },
  {
    name: 'Droit Civil: Manuel Pratique',
    price: 58.5,
    category: 'books',
    description: 'Manuel de droit civil tunisien',
    tags: ['law', 'civil-law', 'legal'],
    inStock: true,
  },
  {
    name: 'Thermodynamique: Exercices Corrigés',
    price: 35.0,
    category: 'books',
    description: 'Exos et solutions en thermodynamique',
    tags: ['physics', 'thermodynamics', 'engineering'],
    inStock: true,
  },
  {
    name: 'Chimie Organique: Réactions Et Mécanismes',
    price: 62.5,
    category: 'books',
    description: 'Guide complet de chimie organique',
    tags: ['chemistry', 'science', 'exam'],
    inStock: true,
  },
  {
    name: 'Biologie Cellulaire Moderne',
    price: 72.0,
    category: 'books',
    description: 'Cours contemporain de biologie cellulaire',
    tags: ['biology', 'science', 'medicine'],
    inStock: true,
  },
  {
    name: 'Français: Grammaire Et Littérature',
    price: 42.0,
    category: 'books',
    description: 'Grammaire française et analyse littéraire',
    tags: ['french', 'language', 'literature'],
    inStock: true,
  },
  {
    name: 'English Grammar and Writing Skills',
    price: 48.5,
    category: 'books',
    description: 'Grammaire anglaise et techniques d\'écriture',
    tags: ['english', 'language', 'writing'],
    inStock: true,
  },
  {
    name: 'Économie: Micro et Macro',
    price: 55.0,
    category: 'books',
    description: 'Introduction à l\'économie micro et macro',
    tags: ['economics', 'business', 'theory'],
    inStock: true,
  },
  {
    name: 'Arts: Histoire Et Mouvements',
    price: 52.0,
    category: 'books',
    description: 'Étude des mouvements artistiques majeurs',
    tags: ['arts', 'history', 'culture'],
    inStock: true,
  },
  {
    name: 'Journal d\'Études Et Notes Quotidiennes',
    price: 28.0,
    category: 'books',
    description: 'Journal structuré pour tracker progression',
    tags: ['journal', 'organization', 'planning'],
    inStock: true,
  },

  // STUDY SNACKS (10 products)
  {
    name: 'Barres Protéinées Énergisantes (Lot 12)',
    price: 18.5,
    category: 'study snacks',
    description: 'Barres nutritives pour énergie prolongée',
    tags: ['energy', 'protein', 'snack', 'health'],
    inStock: true,
  },
  {
    name: 'Café Soluble Premium (250g)',
    price: 12.0,
    category: 'study snacks',
    description: 'Café soluble pour rester alerte',
    tags: ['caffeine', 'beverage', 'focus'],
    inStock: true,
  },
  {
    name: 'Mélange Oléagineux Noix',
    price: 14.5,
    category: 'study snacks',
    description: 'Mix de noix et fruits secs riches en oméga-3',
    tags: ['nuts', 'brain-health', 'snack'],
    inStock: true,
  },
  {
    name: 'Thé Vert Détox (20 Sachets)',
    price: 8.5,
    category: 'study snacks',
    description: 'Thé vert pour relaxation et focus',
    tags: ['tea', 'antioxidant', 'beverage'],
    inStock: true,
  },
  {
    name: 'Chocolat Noir 70% (Lot 5)',
    price: 16.0,
    category: 'study snacks',
    description: 'Chocolat noir pour dopamine et concentration',
    tags: ['chocolate', 'mood', 'snack'],
    inStock: true,
  },
  {
    name: 'Complément Magnésium Poudre',
    price: 19.5,
    category: 'study snacks',
    description: 'Magnésium pour réduire stress et anxiété',
    tags: ['supplement', 'stress-relief', 'health'],
    inStock: true,
  },
  {
    name: 'Biscuits Complets Énergie',
    price: 7.8,
    category: 'study snacks',
    description: 'Biscuits complets légers et énergétiques',
    tags: ['biscuit', 'carbs', 'snack'],
    inStock: true,
  },
  {
    name: 'Jus Frais Antioxydant (1L)',
    price: 6.5,
    category: 'study snacks',
    description: 'Jus riche en vitamines et antioxydants',
    tags: ['juice', 'vitamin', 'beverage', 'health'],
    inStock: true,
  },
  {
    name: 'Chewing-Gum Menthe Fraîche',
    price: 3.2,
    category: 'study snacks',
    description: 'Chewing-gum menthe pour rester alerte',
    tags: ['gum', 'focus', 'freshness'],
    inStock: true,
  },
  {
    name: 'Électrolytes Boisson Isotonique',
    price: 5.5,
    category: 'study snacks',
    description: 'Boisson isotonique pour hydratation optimale',
    tags: ['hydration', 'electrolyte', 'sports'],
    inStock: true,
  },

  // PLANNERS & ORGANIZATION TOOLS (12 products)
  {
    name: 'Agenda Annuel 2025 Luxe',
    price: 32.5,
    category: 'planners & organization tools',
    description: 'Agenda complet pour planifier année entière',
    tags: ['planning', 'organization', 'time-management'],
    inStock: true,
  },
  {
    name: 'Planner Mensuel Réutilisable',
    price: 18.0,
    category: 'planners & organization tools',
    description: 'Planner effaçable pour organiser mois par mois',
    tags: ['planning', 'reusable', 'organization'],
    inStock: true,
  },
  {
    name: 'Tableau Blanc Magnétique 60x40',
    price: 22.5,
    category: 'planners & organization tools',
    description: 'Tableau blanc pour brainstorming et planning',
    tags: ['whiteboard', 'planning', 'brainstorm'],
    inStock: true,
  },
  {
    name: 'Boîte Rangement Modulable (5 Compartiments)',
    price: 15.8,
    category: 'planners & organization tools',
    description: 'Boîte de rangement pour organiser documents',
    tags: ['storage', 'organization', 'filing'],
    inStock: true,
  },
  {
    name: 'Calendrier Mural Académique',
    price: 12.0,
    category: 'planners & organization tools',
    description: 'Calendrier adapté à l\'année académique',
    tags: ['calendar', 'planning', 'dates'],
    inStock: true,
  },
  {
    name: 'Fiches de Révision Colorées (500)',
    price: 14.5,
    category: 'planners & organization tools',
    description: 'Lot de 500 fiches de révision colorées',
    tags: ['studying', 'revision', 'flashcards'],
    inStock: true,
  },
  {
    name: 'Gestionnaire de Tâches Numérique (App Offline)',
    price: 9.5,
    category: 'planners & organization tools',
    description: 'Guide pour utiliser apps de gestion de tâches',
    tags: ['productivity', 'digital', 'task-management'],
    inStock: true,
  },
  {
    name: 'Diagramme Mural Étude (Affiche)',
    price: 8.5,
    category: 'planners & organization tools',
    description: 'Affiche motivante pour bureau d\'étude',
    tags: ['motivation', 'decoration', 'study'],
    inStock: true,
  },
  {
    name: 'Porte-Document Vertical Organiser',
    price: 16.5,
    category: 'planners & organization tools',
    description: 'Organizer vertical pour ranger documents',
    tags: ['storage', 'organization', 'filing'],
    inStock: true,
  },
  {
    name: 'Timeline Board Étude',
    price: 13.0,
    category: 'planners & organization tools',
    description: 'Tableau pour timeline projets et révisions',
    tags: ['planning', 'timeline', 'management'],
    inStock: true,
  },
  {
    name: 'Minuteur Sablier 60 Minutes',
    price: 7.8,
    category: 'planners & organization tools',
    description: 'Sablier pour technique Pomodoro',
    tags: ['time-management', 'focus', 'studying'],
    inStock: true,
  },
  {
    name: 'Banneau d\'Affichage Liège 90x60',
    price: 25.0,
    category: 'planners & organization tools',
    description: 'Tableau liège pour épingler documents importants',
    tags: ['organization', 'filing', 'display'],
    inStock: true,
  },

  // DIGITAL TOOLS (10 products)
  {
    name: 'License Microsoft Office 365 (1 An)',
    price: 75.0,
    category: 'digital tools',
    description: 'Suite Office compète (Word, Excel, PowerPoint)',
    tags: ['software', 'productivity', 'office'],
    inStock: true,
  },
  {
    name: 'Notion Premium (1 Mois)',
    price: 14.0,
    category: 'digital tools',
    description: 'Abonnement Notion pour organisation numérique',
    tags: ['productivity', 'organization', 'app'],
    inStock: true,
  },
  {
    name: 'Grammarly Premium (1 An)',
    price: 48.0,
    category: 'digital tools',
    description: 'Vérification grammaire et style pour écriture',
    tags: ['writing', 'grammar', 'editing'],
    inStock: true,
  },
  {
    name: 'Canva Pro (1 An)',
    price: 52.5,
    category: 'digital tools',
    description: 'Design graphique pour présentations',
    tags: ['design', 'presentation', 'creativity'],
    inStock: true,
  },
  {
    name: 'CorelDRAW License (Perpetuelle)',
    price: 128.0,
    category: 'digital tools',
    description: 'Logiciel dessin vectoriel professionnel',
    tags: ['design', 'graphic', 'software'],
    inStock: true,
  },
  {
    name: 'Adobe CC Suite Student (1 An)',
    price: 156.0,
    category: 'digital tools',
    description: 'Suite Adobe complète avec tarif étudiant',
    tags: ['design', 'video', 'software'],
    inStock: true,
  },
  {
    name: 'Duolingo Plus (1 An)',
    price: 35.0,
    category: 'digital tools',
    description: 'Apprentissage langues sans publicités',
    tags: ['language', 'learning', 'app'],
    inStock: true,
  },
  {
    name: 'ChatGPT Plus (1 Mois)',
    price: 24.0,
    category: 'digital tools',
    description: 'Accès prioritaire à ChatGPT avec GPT-4',
    tags: ['ai', 'writing', 'research'],
    inStock: true,
  },
  {
    name: 'StdFile - Stockage Cloud 2TB',
    price: 68.0,
    category: 'digital tools',
    description: 'Stockage cloud sécurisé 2TB pour 1 an',
    tags: ['cloud', 'storage', 'backup'],
    inStock: true,
  },
  {
    name: 'Ressources Bibliothèque Numérique (Accès 1 An)',
    price: 45.0,
    category: 'digital tools',
    description: 'Accès à 10,000+ études et recherches',
    tags: ['research', 'academic', 'digital'],
    inStock: true,
  },
];

async function seedDatabase() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing products
    await Product.deleteMany({});
    console.log('🗑️ Cleared existing products');

    // Insert new products
    await Product.insertMany(seedProducts);
    console.log(`✅ Seeded ${seedProducts.length} products successfully`);

    // Count by category
    const categoryCounts = await Promise.all(
      ['stationery', 'electronics', 'books', 'study snacks', 'planners & organization tools', 'digital tools'].map(
        async (cat) => ({
          category: cat,
          count: await Product.countDocuments({ category: cat }),
        })
      )
    );

    console.log('\n📊 Products by Category:');
    categoryCounts.forEach((c) => console.log(`   ${c.category}: ${c.count}`));

    await mongoose.connection.close();
    console.log('\n✅ Seeding completed!');
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
}

seedDatabase();
